#!/usr/bin/env ruby

# frozen_string_literal: true

# Ascii artをエンコードするプログラム
# HOW TO USE
# 1. Ascii artを作成する
# ./convert.rb <Ascii art file> <debug mode>

filename = ARGV[0]
is_debug_mode = !ARGV[1].nil?
f = File.read(filename)
aa = f.chars.map do |t|
  if t == ' '
    0
  elsif t == "\n"
    t
  else
    1
  end
end.join('')

bits = aa.gsub("\n", "").reverse.to_i(2)

width = aa.split("\n").first.size
height = aa.split("\n").size

bin = [Marshal.dump(bits)].pack('m').gsub("\n", ' ')

# for debug
if is_debug_mode
  STDERR.print "\e[32m" # start green color
  STDERR.puts "=========================="
  STDERR.puts "converter information"
  STDERR.puts ""
  STDERR.print "\e[0m" # stop color

  STDERR.puts "==== program info ==="
  STDERR.puts "  width #{width}, height #{height}"
  STDERR.puts "  program limits is #{aa.count('1')}"
  STDERR.puts ""

  STDERR.puts "==== bits ==="
  STDERR.puts "  bits #{bits}"
  STDERR.puts "  bits size: #{bits.size}"
  STDERR.puts ""

  STDERR.puts "==== data ==="
  STDERR.puts "  data byte: #{bin}"
  STDERR.puts "  data size: #{bin.length}"
  STDERR.puts ""
end

puts "#{width}"
puts "#{height}"
puts "#{bin}"
