#!/usr/bin/env ruby

if ARGV.size < 1
  puts "Usage: ruby generate_quine.rb <program_file>"
  exit 1
end

program_file = ARGV[0]
width, height, encoded_data = $stdin.read.lines

program = File.read(program_file)

header = <<RUBY
eval$s=%w'
e="eval$s=%w"<<39<<($s*1000)
d="#{encoded_data}"
w=#{width}
h=#{height}
RUBY

footer = <<RUBY
#'.join
RUBY

# コメント行を削除
program = program.lines.reject { |it| it.start_with?("#") }.join

# 一行のプログラムに変換する
quine = (header + program + footer).lines.map{ |it| it.strip }.join(";")

puts quine
